[build]
    command = "npm run build"
    publish = "dist"

[functions]
    directory = "functions"

[dev]
    command = "npm run serve"
    targetPort = 8080
    port = 8081
    autoLaunch = true

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
   from = "/*"
   to = "/errors/404/index.html"
   status = 404